name: CC Extensions
markdown: kramdown
highlighter: rouge
url: http://www.cc-extensions.com
author: Davide Barranca
description: Photoshop Extensions and Scripts
include: ['.htaccess']
timezone: Europe/Rome
gems: [jekyll-paginate]
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/rss.xml"
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
paginate: 5
paginate_path: "/news/page:num"
permalink: /news/:year/:month/:title/index.html